import Navigation from "../components/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// next.js는 layout를 먼저 렌더링한 뒤 하위 요소 렌더링!
// 하위 요소 : url을 확인하여 렌더링하는 것

// 기존 React 방식에서 사용했던 Layout을 위한 App에서 사용했던 Route 같은 개념

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
